//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionsReport
    {
        public int ReportId { get; set; }
        public int OperationId { get; set; }
        public int ComputerId { get; set; }
        public string ActionName { get; set; }
        public bool IsFromLan { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime DateCompleteOrError { get; set; }
        public string Result { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual ShopComputer ShopComputer { get; set; }
    }
}
