//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerErrorsLogView
    {
        public int ErrorId { get; set; }
        public string ShopId { get; set; }
        public int ComputerId { get; set; }
        public string ComputerName { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public string Mac { get; set; }
    }
}
