//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.ActionsReports = new HashSet<ActionsReport>();
            this.OperationsStates = new HashSet<OperationsState>();
        }
    
        public int ID { get; set; }
        public int ComputerId { get; set; }
        public int OperationType { get; set; }
        public string Attributes { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> PoolDate { get; set; }
        public Nullable<System.Guid> GroupGUID { get; set; }
        public Nullable<bool> IsFromSheduler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionsReport> ActionsReports { get; set; }
        public virtual OperationType OperationType1 { get; set; }
        public virtual ShopComputer ShopComputer { get; set; }
        public virtual OperationsReport OperationsReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsState> OperationsStates { get; set; }
    }
}
