//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsState
    {
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int OperStateId { get; set; }
        public System.DateTime StateDate { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual OperationStatesVoc OperationStatesVoc { get; set; }
    }
}
