//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationTypeAttribute
    {
        public int Id { get; set; }
        public int OperationTypeId { get; set; }
        public int UserId { get; set; }
        public string Attributes { get; set; }
    
        public virtual OperationType OperationType { get; set; }
        public virtual User User { get; set; }
    }
}
