//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceCounter
    {
        public int ComputerId { get; set; }
        public System.DateTime DateTimeUtc { get; set; }
        public int ParameterId { get; set; }
        public double ParameterValue { get; set; }
    
        public virtual PerformanceCounterDictionary PerformanceCounterDictionary { get; set; }
        public virtual ShopComputer ShopComputer { get; set; }
    }
}
