//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShedulerTasksComputersList
    {
        public int TaskId { get; set; }
        public int ComputerId { get; set; }
    
        public virtual ShedulerTask ShedulerTask { get; set; }
    }
}
