//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShedulerTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShedulerTask()
        {
            this.ShedulerSteps = new HashSet<ShedulerStep>();
            this.ShedulerTaskHistories = new HashSet<ShedulerTaskHistory>();
            this.ShedulerTasksComputersLists = new HashSet<ShedulerTasksComputersList>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> FirstStepId { get; set; }
        public int Mode { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime NextStartTime { get; set; }
        public Nullable<System.DateTime> LastStartTime { get; set; }
        public Nullable<System.DateTime> LastEndTime { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDateUtc { get; set; }
        public string CreatedUserLogin { get; set; }
        public Nullable<int> RepeatValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShedulerStep> ShedulerSteps { get; set; }
        public virtual ShedulerStep ShedulerStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShedulerTaskHistory> ShedulerTaskHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShedulerTasksComputersList> ShedulerTasksComputersLists { get; set; }
        public virtual ShedulerStatus ShedulerStatus { get; set; }
        public virtual ShedulerTaskMode ShedulerTaskMode { get; set; }
    }
}
