//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShedulerPluginTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public int Mode { get; set; }
        public System.DateTime NextStartTime { get; set; }
        public Nullable<System.DateTime> LastStartTime { get; set; }
        public Nullable<System.DateTime> LastEndTime { get; set; }
        public int Status { get; set; }
        public string PluginFileName { get; set; }
        public Nullable<int> RepeatValue { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDateUtc { get; set; }
        public string CreatedUserLogin { get; set; }
    
        public virtual ShedulerStatus ShedulerStatus { get; set; }
        public virtual ShedulerTaskMode ShedulerTaskMode { get; set; }
    }
}
