//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShedulerStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShedulerStep()
        {
            this.ShedulerTaskHistories = new HashSet<ShedulerTaskHistory>();
            this.ShedulerTasks = new HashSet<ShedulerTask>();
        }
    
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int OperationType { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public Nullable<int> RepeatTimeout { get; set; }
        public int OperationCheckIntervalMs { get; set; }
        public int OnOperationCompleteStep { get; set; }
        public int OnOperationErrorStep { get; set; }
        public int OrderId { get; set; }
        public string OperationAttributes { get; set; }
    
        public virtual ShedulerTask ShedulerTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShedulerTaskHistory> ShedulerTaskHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShedulerTask> ShedulerTasks { get; set; }
    }
}
