//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopComputer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopComputer()
        {
            this.ActionsReports = new HashSet<ActionsReport>();
            this.ComputerErrorsLogs = new HashSet<ComputerErrorsLog>();
            this.LocalSettings = new HashSet<LocalSetting>();
            this.Logs1C = new HashSet<Logs1C>();
            this.Operations = new HashSet<Operation>();
        }
    
        public int ComputerId { get; set; }
        public string ShopId { get; set; }
        public string ComputerName { get; set; }
        public string ComputerAddress { get; set; }
        public bool Is1CServer { get; set; }
        public bool IsMainCashbox { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ComputerHash { get; set; }
        public string Mac { get; set; }
        public string MagicUpdaterVersion { get; set; }
        public string External_IP { get; set; }
        public Nullable<bool> IsTaskerAlive { get; set; }
        public Nullable<bool> IsSettingsRead { get; set; }
        public int IsON { get; set; }
        public string LastError { get; set; }
        public Nullable<bool> IsAgentSettingsReaded { get; set; }
        public Nullable<System.DateTime> LastErrorDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionsReport> ActionsReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComputerErrorsLog> ComputerErrorsLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalSetting> LocalSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs1C> Logs1C { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
