//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShedulerStep
    {
        public int taskId { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public int IsChildPositiveBranch { get; set; }
    }
}
