//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOperState
    {
        public int OperationId { get; set; }
        public int OperationType { get; set; }
        public string ShopId { get; set; }
        public string ComputerName { get; set; }
        public int OperStateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StateDate { get; set; }
    }
}
