//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShedulerStepsVi
    {
        public int Id { get; set; }
        public Nullable<long> Step { get; set; }
        public int TaskId { get; set; }
        public int OperationType { get; set; }
        public string Name { get; set; }
        public string NameRus { get; set; }
        public string nameVis { get; set; }
        public string nameVisCount { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public Nullable<int> RepeatTimeout { get; set; }
        public int OperationCheckIntervalMs { get; set; }
        public int OnOperationCompleteStep { get; set; }
        public string NameCompleteStep { get; set; }
        public string NameRusCompleteStep { get; set; }
        public string nameVisCompleteStep { get; set; }
        public string nameVisCountCompleteStep { get; set; }
        public int OnOperationErrorStep { get; set; }
        public string NameErrorStep { get; set; }
        public string NameRusErrorStep { get; set; }
        public string nameVisErrorStep { get; set; }
        public string nameVisCountErrorStep { get; set; }
        public int OrderId { get; set; }
        public string OperationAttributes { get; set; }
    }
}
