//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOperationsLight
    {
        public int ID { get; set; }
        public string OperationTypeEn { get; set; }
        public string OperationTypeRu { get; set; }
        public int ComputerId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> OperStateId { get; set; }
        public string OperState { get; set; }
        public int Is1CError { get; set; }
    }
}
