//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewComputerErrorsLog
    {
        public int ErrorId { get; set; }
        public int ComputerId { get; set; }
        public string ComputerName { get; set; }
        public string External_IP { get; set; }
        public bool Is1CServer { get; set; }
        public bool IsMainCashbox { get; set; }
        public Nullable<bool> IsTaskerAlive { get; set; }
        public int IsON { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime ErrorDate { get; set; }
    }
}
