//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicUpdater.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShopComputersServer
    {
        public Nullable<int> ComputerId { get; set; }
        public string ShopId { get; set; }
        public string ShopName { get; set; }
        public string ShopRegion { get; set; }
        public Nullable<bool> ExchangeError { get; set; }
        public string AddressToConnect { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastSuccessfulUpload { get; set; }
        public Nullable<System.DateTime> LastSuccessfulReceive { get; set; }
        public string ComputerName { get; set; }
        public string ComputerAddress { get; set; }
        public bool Is1CServer { get; set; }
        public bool IsMainCashbox { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ComputerHash { get; set; }
        public string Mac { get; set; }
        public string MagicUpdaterVersion { get; set; }
        public string External_IP { get; set; }
        public bool IsTaskerAlive { get; set; }
        public int IsON { get; set; }
        public string OperationTypeRu { get; set; }
        public Nullable<System.DateTime> OperationCreationDate { get; set; }
        public string OperState { get; set; }
        public string LastError { get; set; }
        public Nullable<System.DateTime> LastErrorDate { get; set; }
        public Nullable<System.DateTime> AvgPerformanceCounterValuesDateTimeUtc { get; set; }
        public Nullable<double> AvgCpuTime { get; set; }
        public Nullable<double> AvgRamAvailableMBytes { get; set; }
        public Nullable<double> AvgDiskQueueLength { get; set; }
        public string HwId { get; set; }
        public string LicId { get; set; }
        public Nullable<int> LicStatus { get; set; }
    }
}
